M48
; DRILL file {KiCad 7.0.9} date Sun Nov 12 02:22:47 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-12T02:22:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0360
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.725Y-3.42
X5.725Y-3.82
X5.825Y-3.42
X5.825Y-3.82
X5.925Y-3.42
X5.925Y-3.82
T2
X5.625Y-3.42
X5.625Y-3.82
T0
M30
